### PR TITLE
New IDE blog post: The performance of ghcide 0.2.0

### PR DESCRIPTION
**Pull request by pepeiborra**
Ready for review @bubba

### CODE REVIEW

**Comment by pepeiborra** [comment]
How can we see if the embedded script is rendered correctly in Matt's site?

**Comment by lukel97** [comment]
You can execute `site.hs` as a script, and off the top of my head `./site.hs watch` should spin up a development server on localhost

**Review by lukel97 — APPROVED** [review]
Sorry for the delay, reviewing this from my phone but looks good! Did it render ok locally?

**Comment by pepeiborra** [comment]
It does render correctly now, after adjusting some of the images paths. Good to go!

**Pull request merged**
